/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.awt.TextArea;
import java.time.LocalDate;
import subclasses.Product;
import subclasses.Sale;
import subclasses.Store;

/**
 *
 * @author pc
 */
public class SalesReportPanel extends javax.swing.JFrame {

    /**
     * Creates new form SalesReportPanel
     */
    public SalesReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        daily = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        monthly = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        year = new javax.swing.JSpinner();
        month = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daily.setText("Daily Report");
        daily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyActionPerformed(evt);
            }
        });
        jPanel1.add(daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 190, 43));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, 190, 42));

        reportArea.setColumns(20);
        reportArea.setRows(5);
        jScrollPane1.setViewportView(reportArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 34, 347, 321));

        monthly.setText("Monthly Report");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        jPanel1.add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, 190, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Day/Month/Year");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 181, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Report Sheet");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 340, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, -1));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 80, -1));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skin color.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyActionPerformed
        // TODO add your handling code here:

        int day = (Integer) date.getValue();
        int month = (Integer) this.month.getValue();
        int year = (Integer) this.year.getValue();
        if (day != 0 && month != 0 && year != 0) {
            LocalDate selectedDate = LocalDate.of(year, month, day);
            double dailyProfit = Store.dalyPro(selectedDate);
            reportArea.setText("");
            for (Sale sale : Store.getAllSales()) {
                if (sale.getDate().equals(selectedDate)) {
                    Product product = sale.getProduct();
                    int quantitySold = sale.getQuantitySold();
                    double sellingPrice = product.getSellingp();
                    double totalPrice = sellingPrice * quantitySold;
                    reportArea.setText(String.format("Product: %s, Quantity Sold: %d, Total Price: %.2f\n",
                            product.getName(), quantitySold, totalPrice));
                }
            }
            reportArea.setText("\nDaily Profit for " + selectedDate + ": " + String.format("%.2f", dailyProfit));
        } else {
            Store.showMsgError("Enter the date first..!");
        }
    }//GEN-LAST:event_dailyActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        AdminMenu a = new AdminMenu();
        a.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
        int month = (Integer) this.month.getValue();
        int year = (Integer) this.year.getValue();
        if (month != 0 && year != 0) {
            double monthlypro = Store.monthlyPro(month, year);
            reportArea.setText("");

            for (Sale sale : Store.getAllSales()) {
                if (sale.getDate().getMonthValue() == month && sale.getDate().getYear() == year) {
                    Product product = sale.getProduct();
                    int quantitySold = sale.getQuantitySold();
                    double sellingPrice = product.getSellingp();
                    double totalPrice = sellingPrice * quantitySold;
                
                    reportArea.setText(String.format("Product: %s, Quantity Sold: %d, Total Price: %.2f\n",
                            product.getName(), quantitySold, totalPrice));
                }
            }

            
            reportArea.setText("\nMonthly Profit for " + month + "/" + year + ": " + String.format("%.2f", monthlypro));
        } else {
            Store.showMsgError("Enter the date first..!");
        }

    }//GEN-LAST:event_monthlyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReportPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReportPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReportPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReportPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReportPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton daily;
    private javax.swing.JSpinner date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner month;
    private javax.swing.JButton monthly;
    private javax.swing.JTextArea reportArea;
    private javax.swing.JSpinner year;
    // End of variables declaration//GEN-END:variables
}
